sudo: true
dist: trusty

rvm:
  - 2.3.4

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - cd image && sudo ruby build.rb
