sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -f ./image/base/Dockerfile -t discourse-test-image .
      - docker images
      - docker tag discourse-test-image $DOCKER_USERNAME/discourse-test-image
      - docker push $DOCKER_USERNAME/discourse-test-image

